### ISSUE TITLE
Missing opcodes

### ISSUE THREAD

**Issue by franfrandev** [wuwe1/vim-huff#1]
Hello sir!

Very useful plugin !
Though it appears to be relying on external sources which sometimes lacks of data.
For example, `selfbalance` cannot be looked up because it seems like it has been forgotten on "https://raw.githubusercontent.com/huff-language/vscode-huff/master/src/features/hover/asm.json".
Would it be a good choice to store the JSON file locally instead, so the plugin will keep working even if the resources has been moved ?

Thanks again

**Comment by wuwe1** [comment]
Good catch! I actually hardcode the JSON file in the [code](https://github.com/wuwe1/vim-huff/blob/40a40ed80f945474bfd1b032621822735b2ccfc2/autoload/evm/lookup.vim#L53).
